# Generated by Django 5.1 on 2024-08-24 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_project_id_alter_ticket_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='responsible_user',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name__in', ['analista', 'dev'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sin empezar'), (2, 'En proceso'), (3, 'Testeando'), (4, 'Listo')]),
        ),
    ]
