# Generated by Django 5.1 on 2024-09-02 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_casocontenido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name__in', ['analista', 'dev'])), null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
