# Generated by Django 5.1 on 2024-09-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_caso_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casocontenido',
            name='pasos',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='casocontenido',
            name='precondicion',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='casocontenido',
            name='resultados_esperados',
            field=models.TextField(max_length=150),
        ),
    ]
