# Generated by Django 5.1 on 2024-09-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_casocontenido_pasos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='pasos',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='precondicion',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='caso',
            name='resultados_esperados',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='CasoContenido',
        ),
    ]
