# Generated by Django 5.0.7 on 2024-09-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_caso_pasos_caso_precondicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='title',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
