# Generated by Django 5.0.7 on 2024-09-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_caso_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caso',
            old_name='title',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='caso',
            name='prioridad',
            field=models.CharField(choices=[('1', 'bajo'), ('2', 'medio'), ('3', 'alto'), ('4', 'critico')], max_length=1),
        ),
        migrations.AlterField(
            model_name='caso',
            name='tipo',
            field=models.CharField(choices=[('1', 'accesibilidad'), ('2', 'automatización'), ('3', 'compatibilidad'), ('4', 'funcional'), ('5', 'rendimiento'), ('6', 'seguridad'), ('7', 'usabilidad'), ('8', 'otro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Testing'), (4, 'Done')], max_length=1),
        ),
    ]
