# Generated by Django 5.0.7 on 2024-09-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_comment_ticket_delete_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='titulo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
