# Generated by Django 5.0.7 on 2024-09-04 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_caso_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caso'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='estimado',
            field=models.CharField(max_length=10),
        ),
    ]
