# Generated by Django 5.0.7 on 2024-09-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_comment_caso_alter_caso_estimado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='caso',
        ),
    ]
