# Generated by Django 5.0.7 on 2024-09-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_comment_caso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
