# Generated by Django 5.0.7 on 2024-09-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_comment_caso'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='estado',
            field=models.CharField(choices=[('1', 'Aprobado'), ('2', 'Bloqueado'), ('4', 'Retesteado'), ('1', 'Fallido')], default=1, max_length=1),
        ),
    ]
