# Generated by Django 5.0.7 on 2024-09-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_caso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='prioridad',
            field=models.CharField(choices=[('1', 'bajo'), ('2', 'medio'), ('3', 'alto'), ('4', 'critico')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='caso',
            name='tipo',
            field=models.CharField(choices=[('1', 'accesibilidad'), ('2', 'automatización'), ('3', 'compatibilidad'), ('4', 'funcional'), ('5', 'rendimiento'), ('6', 'seguridad'), ('7', 'usabilidad'), ('8', 'otro')], default=1, max_length=1),
        ),
    ]
