# Generated by Django 5.0.7 on 2024-09-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_caso_estado_alter_caso_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='estado',
            field=models.CharField(choices=[('1', 'Sin Empezar'), ('2', 'Aprobado'), ('3', 'Bloqueado'), ('4', 'Retesteado'), ('5', 'Fallido')], default=1, max_length=1),
        ),
    ]
