# Generated by Django 5.1 on 2024-09-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_caso_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comentario',
        ),
    ]
