# Generated by Django 5.1 on 2024-09-09 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_content_comment_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='estado',
            field=models.CharField(choices=[('1', 'Sin Ejecutar'), ('2', 'Aprobado'), ('3', 'Bloqueado'), ('4', 'Retesteado'), ('5', 'Fallido')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='caso',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name__in', ['analista', 'dev'])), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
