# Generated by Django 5.1.1 on 2024-09-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_document_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='documento',
        ),
    ]
