# Generated by Django 5.1.1 on 2024-09-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rename_document_document_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='documento',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
