# Generated by Django 5.1.1 on 2024-09-20 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_project_responsible_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='project',
            name='responsible_user',
        ),
        migrations.AddField(
            model_name='project',
            name='responsible_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'analista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
