# Generated by Django 5.1.1 on 2024-09-21 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_project_users_remove_project_responsible_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'analista'}, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
