# Generated by Django 5.1.1 on 2024-09-21 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_project_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('groups__name__in', ['analista', 'dev'])), related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
