# Generated by Django 5.1.1 on 2024-09-21 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_project_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
    ]
