# Generated by Django 5.1.1 on 2024-09-25 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_project_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='desarrollador',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name__in', 'dev')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
