# Generated by Django 5.0.7 on 2024-09-25 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_project_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caso'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caso'),
        ),
    ]
