# Generated by Django 5.1.1 on 2024-09-25 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_caso_desarrollador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caso'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caso'),
        ),
    ]
