# Generated by Django 5.0.7 on 2024-09-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_comment_caso_alter_image_caso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='desarrollador',
        ),
    ]
