# Generated by Django 5.0.7 on 2024-09-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_caso_desarrollador'),
        ('core', '0044_remove_comment_desarrollador'),
    ]

    operations = [
    ]
