# Generated by Django 5.0.7 on 2024-09-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_merge_20240926_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='pasos',
        ),
        migrations.AddField(
            model_name='caso',
            name='descripcion',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='precondicion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
