# Generated by Django 5.1.1 on 2024-10-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_caso_pasos_caso_descripcion_and_more'),
    ]

    operations = [
    ]
