# Generated by Django 5.1.1 on 2024-10-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_image_image'),
    ]

    operations = [
    ]
